In [5]:
import pandas as pd

df = pd.DataFrame(
    {
        "track": ["Python", "SQL", "Python", "C", "SQL", "Python"],
        "score": [78.0, 88.0, 92.0, 85.0, None, 88.0],
        "minutes": [25, 32, 20, 28, 18, 30],
    },
    index=["s1", "s2", "s3", "s4", "s5", "s6"],
)
df

     track  score  minutes
s1  Python   78.0       25
s2     SQL   88.0       32
s3  Python   92.0       20
s4       C   85.0       28
s5     SQL    NaN       18
s6  Python   88.0       30

In [4]:
def filter_candidates(
    df: pd.DataFrame,
    min_score: float,
    tracks: list[str],
    min_minutes: float,
    max_minutes: float,
) -> pd.DataFrame:
    if min_minutes>max_minutes:
        raise ValueError("min_minutes must be less than max_minutes")
    mask=(
        (df['score'].notna())&
        (df['score']>=min_score) &
        (df['track'].isin(tracks))&
        (df['minutes']>=min_minutes)&
        (df['minutes']<=max_minutes)
    )
    return df.loc[mask,['track','score','minutes']]
filter_candidates(df, 80, ["Python", "SQL"], 20, 30)

     track  score  minutes
s3  Python   92.0       20
s6  Python   88.0       30

In [10]:
def select_label_block(
    df: pd.DataFrame,
    start_label,
    stop_label,
    columns: list[str],
) -> pd.DataFrame:
    if any((columns[i]==columns[j]) & (i !=j)
    for i in range(len(columns))
    for j in range(len(columns))):
        raise ValueError("columns must be unique")
    if start_label not in df.index or stop_label not in df.index:
        raise ValueError("start_label and stop_label must be in df.columns")
    mask=(
        (df.index>=start_label)&
        (df.index<=stop_label)
    )
    return df.loc[mask,columns]
select_label_block(df, "s2", "s4", ["score", "minutes"])
# 索引 s2、s3、s4；两端都包含

    score  minutes
s2   88.0       32
s3   92.0       20
s4   85.0       28

In [17]:
import numpy as np
def take_positions(
    df: pd.DataFrame,
    row_positions: list[int],
    column_positions: list[int],
) -> pd.DataFrame:
    if any(type(row_positions[i]) !=int
    for i in range(len(row_positions))):
        raise ValueError("row_positions must be integers")
    if any(type(column_positions[i]) !=int
    for i in range(len(column_positions))):
        raise ValueError("row_positions must be integers")
    
    return df.iloc[row_positions,column_positions]
take_positions(df, [2,0,-1], [1,2])

    score  minutes
s3   92.0       20
s1   78.0       25
s6   88.0       30